### ISSUE TITLE
Issue adapting your example code to own data.

### ISSUE THREAD

**Issue by tolender** [yancychy/DiffChIPL#2]
Hi,
I am trying to get your example code to work on my own data. I am getting this error. Any idea what is wrong?

**> resA = DiffChIPL(cpmD, design0, group0 = group )
Error in model.frame.default(formula = y ~ x + w, drop.unused.levels = TRUE) : 
  variable lengths differ (found for 'x')**

Thanks!

**Comment by yancychy** [comment]
Hi, it seems the data sample number are different in either cpmD, design0, or group.

**Comment by tolender** [comment]
Hi,
I used your example code exactly with my samples, with 2xCTRL and 2xTreatment. I even renamed the ctrl and treatment to sim1/sim2. Is this matrix correct for design0?

     sim2 sim1
[1,]    1    1
[2,]    1    1
[3,]    1    0
[4,]    1    0

**Comment by yancychy** [comment]
Maybe it is caused by NA value in the data. Please remove the rows which contain NA values. 
https://stackoverflow.com/questions/19771284/error-in-model-frame-default-variable-lengths-differ

**Comment by tolender** [comment]
I checked over the cpmD array and it does not contain "NA" values.

**Comment by adoe21** [comment]
I've gotten the same error, and I've traced it back to the filtLowCounts function within the DiffChIPL function. The error occurs when filtLowCounts calls piecewise.linear because the smoothY variable is empty. It appears smoothY is empty due to the line:

smoothY = smoothY[names(sx)]

When running the package on my data, the sx variable has no names resulting in smoothY being empty. What is this names(sx) call doing? If I just get rid of that line, it gets rid of the error, but don't want to be removing a step that may be necessary.

**Comment by yancychy** [comment]
Thanks @adoe21 . I will update it soon.

**Comment by yancychy** [comment]
This step is essential. Because it is will reorder the values of smoothY to be consistent with sx. 
```
smoothY = smoothY[names(sx)]

```

**Comment by adoe21** [comment]
This fixed it thanks!
